// Nigerian States (36 states)
export const nigerianStates = [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
    'FCT (Abuja)',
  ];
  
  // Nigerian Public Universities
  export const nigerianUniversities = [
    'Abubakar Tafawa Balewa University (ATBU), Bauchi',
    'Ahmadu Bello University (ABU), Zaria',
    'Bayero University (BUK), Kano',
    'Federal University, Gashua',
    'Federal University, Gusau',
    'Federal University, Lafia',
    'Federal University, Lokoja',
    'Federal University of Agriculture, Abeokuta',
    'Federal University of Agriculture, Makurdi',
    'Federal University of Petroleum Resources (FUPRE), Effurun',
    'Federal University of Technology, Akure (FUTA)',
    'Federal University of Technology, Minna (FUTMINNA)',
    'Federal University of Technology, Owerri (FUTO)',
    'Federal University, Birnin Kebbi',
    'Federal University, Dutse',
    'Federal University, Dutsin-Ma',
    'Federal University, Kashere',
    'Federal University, Oye-Ekiti',
    'Federal University, Wukari',
    'Michael Okpara University of Agriculture (MOUAU), Umudike',
    'Modibbo Adama University of Technology (MAUTECH), Yola',
    'National Open University of Nigeria (NOUN), Lagos',
    'Nigerian Defence Academy (NDA), Kaduna',
    'Nnamdi Azikiwe University (UNIZIK), Awka',
    'Obafemi Awolowo University (OAU), Ile-Ife',
    'University of Abuja (UNIABUJA), Gwagwalada',
    'University of Benin (UNIBEN), Benin City',
    'University of Calabar (UNICAL), Calabar',
    'University of Ibadan (UI), Ibadan',
    'University of Ilorin (UNILORIN), Ilorin',
    'University of Jos (UNIJOS), Jos',
    'University of Lagos (UNILAG), Lagos',
    'University of Maiduguri (UNIMAID), Maiduguri',
    'University of Nigeria (UNN), Nsukka',
    'University of Port Harcourt (UNIPORT), Port Harcourt',
    'University of Uyo (UNIUYO), Uyo',
    'Usmanu Danfodiyo University (UDUSOK), Sokoto',
    'Adekunle Ajasin University (AAUA), Akungba',
    'Ambrose Alli University (AAU), Ekpoma',
    'Chukwuemeka Odumegwu Ojukwu University (COOU), Uli',
    'Delta State University (DELSU), Abraka',
    'Ebonyi State University (EBSU), Abakaliki',
    'Ekiti State University (EKSU), Ado-Ekiti',
    'Enugu State University of Science and Technology (ESUT), Enugu',
    'Gombe State University (GSU), Gombe',
    'Ibrahim Badamasi Babangida University (IBBU), Lapai',
    'Ignatius Ajuru University of Education (IAUE), Rumuolumeni',
    'Imo State University (IMSU), Owerri',
    'Kaduna State University (KASU), Kaduna',
    'Kano University of Science and Technology (KUST), Wudil',
    'Kebbi State University of Science and Technology (KSUSTA), Aliero',
    'Kogi State University (KSU), Anyigba',
    'Kwara State University (KWASU), Malete',
    'Ladoke Akintola University of Technology (LAUTECH), Ogbomoso',
    'Lagos State University (LASU), Ojo',
    'Nasarawa State University (NSUK), Keffi',
    'Niger Delta University (NDU), Wilberforce Island',
    'Olabisi Onabanjo University (OOU), Ago-Iwoye',
    'Ondo State University of Science and Technology (OSUSTECH), Okitipupa',
    'Osun State University (UNIOSUN), Osogbo',
    'Plateau State University (PLASU), Bokkos',
    'Rivers State University (RSU), Port Harcourt',
    'Sokoto State University (SSU), Sokoto',
    'Taraba State University (TSU), Jalingo',
    'Yobe State University (YSU), Damaturu',
    'Zamfara State University (ZASU), Talata-Mafara',
  ];
  
  // Private Universities - Comprehensive List (147+)
  export const nigerianPrivateUniversities = [
    // Major Private Universities
    'Covenant University (CU), Ota',
    'Babcock University (BU), Ilishan-Remo',
    'Afe Babalola University (ABUAD), Ado-Ekiti',
    'Pan-Atlantic University (PAU), Lagos',
    'American University of Nigeria (AUN), Yola',
    'Igbinedion University (IUO), Okada',
    'Bowen University (BOWEN), Iwo',
    'Redeemer\'s University (RUN), Ede',
    'Ajayi Crowther University (ACU), Oyo',
    'Lead City University (LCU), Ibadan',
    'Madonna University (MU), Okija',
    'Bells University of Technology (BUT), Ota',
    'Baze University (BU), Abuja',
    'Caleb University (CU), Imota',
    'Skyline University (SUN), Kano',
    'Landmark University, Omu-Aran',
    'Elizade University, Ilara-Mokin',
    'Veritas University (The Catholic University of Nigeria), Abuja',
    'Bingham University, Karu',
    'Caritas University, Enugu',
    'Crawford University, Igbesa',
    'Crescent University, Abeokuta',
    'Fountain University, Osogbo',
    'Godfrey Okoye University, Enugu',
    'Gregory University, Uturu',
    'Joseph Ayo Babalola University (JABU), Ikeji-Arakeji',
    'Kings University, Ode Omu',
    'Kwararafa University, Wukari',
    'Mcpherson University, Seriki Sotayo',
    'Novena University, Ogume',
    'Paul University, Awka',
    'Rhema University, Aba',
    'Salem University, Lokoja',
    'Tansian University, Umunya',
    'Wesley University of Science and Technology, Ondo',
    'Western Delta University, Oghara',
    'Achievers University, Owo',
    'Adeleke University, Ede',
    'Al-Hikmah University, Ilorin',
    'Al-Qalam University, Katsina',
    'Augustine University, Ilara',
    'Benson Idahosa University (BIU), Benin City',
    'Chrisland University, Owode',
    'Christopher University, Mowe',
    'Clifford University, Owerrinta',
    'Coal City University, Enugu',
    'Crown Hill University, Eiyenkorin',
    'David Umahi Federal University of Health Sciences, Uburu',
    'Dominion University, Ibadan',
    'Edwin Clark University, Kiagbodo',
    'Evangel University, Akaeze',
    'Glorious Vision University, Ogwa',
    'Greenfield University, Kaduna',
    'Hallmark University, Ijebu-Itele',
    'Havilla University, Nde-Ikom',
    'Kola Daisi University, Ibadan',
    'Legacy University, Okija',
    'Mewar International University, Masaka',
    'Micheal & Cecilia Ibru University, Owhrode',
    'Mountain Top University, Makogi-Ogun',
    'Nile University of Nigeria, Abuja',
    'PAMO University of Medical Sciences, Port Harcourt',
    'Precious Cornerstone University, Ibadan',
    'Renaissance University, Enugu',
    'Ritman University, Ikot Ekpene',
    'Summit University, Offa',
    'Topfaith University, Mkpatak',
    'Trinity University, Yaba',
    'University of Mkar, Mkar',
    'Wellspring University, Irhirhi',
    'Wesley University, Ondo',
    'Yusuf Maitama Sule University, Kano',
    'Anchor University, Ayobo',
    'Arthur Jarvis University, Akpabuyo',
    'Atiba University, Oyo',
    'Ave Maria University, Piyanko',
    'Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti',
    'Capital City University, Kano',
    'Claretian University of Nigeria, Nekede',
    'Confluence University of Science and Technology, Osara',
    'Copperbelt University, Ilorin',
    'Cornerstone University, Lagos',
    'Crown University, Amuwo-Odofin',
    'Eko University of Medical and Health Sciences, Ijanikin',
    'El-Amin International School, Minna',
    'Elegance University, Kano',
    'Epic University, Ibadan',
    'First Technical University, Ibadan',
    'Focus University, Ibadan',
    'Headfort University, Ibadan',
    'James Hope University, Lagos',
    'Karl-Kumm University, Vom',
    'Khalifa Isyaku Rabiu University, Kano',
    'Kingsley Ozumba Mbadiwe University, Ogboko',
    'Lagos State University of Education, Ijanikin',
    'Maryam Abacha American University of Nigeria, Kano',
    'Mercy Medical University, Ibadan',
    'Miva Open University, Abuja',
    'Nigerian British University, Asa',
    'Nigerian University of Technology and Management, Apapa',
    'Nok University, Kachia',
    'Northwest University, Kano',
    'Nova Southeastern University, Abuja',
    'Oduduwa University, Ipetumodu',
    'Peaceland University, Enugu',
    'Pen Resource University, Gombe',
    'Philomath University, Kuje',
    'Platinum University, Anambra',
    'Prime University, Abuja',
    'Rayhaan University, Kebbi',
    'Renaissance University, Ugbawka',
    'Samuel Adegboyega University, Ogwa',
    'Southwestern University, Okun Owa',
    'Spiritan University, Nneochi',
    'Thomas Adewumi University, Oko-Irese',
    'University of Africa, Toru-Orua',
    'University of Offa, Offa',
  ];
  
  // Polytechnics (Public)
  export const nigerianPolytechnicsPublic = [
    'Yaba College of Technology (YABATECH), Lagos',
    'The Polytechnic, Ibadan (IBADAN POLY), Ibadan',
    'Kaduna Polytechnic (KADPOLY), Kaduna',
    'Auchi Polytechnic (AUCHIPOLY), Auchi',
    'Federal Polytechnic, Nekede (NEKEDE POLY), Owerri',
    'Federal Polytechnic, Ilaro (ILARO POLY), Ilaro',
    'Federal Polytechnic, Ado-Ekiti (ADO POLY), Ado-Ekiti',
    'Federal Polytechnic, Offa (OFFA POLY), Offa',
    'Federal Polytechnic, Bauchi (BAUCHI POLY), Bauchi',
    'Federal Polytechnic, Oko (OKO POLY), Oko',
    'Federal Polytechnic, Bida, Niger State',
    'Federal Polytechnic, Ede, Osun State',
    'Federal Polytechnic, Idah, Kogi State',
    'Federal Polytechnic, Kaura Namoda, Zamfara',
    'Federal Polytechnic, Mubi, Adamawa',
    'Federal Polytechnic, Nasarawa, Nasarawa State',
    'Federal Polytechnic, Ukana, Akwa Ibom',
    'Hassan Usman Katsina Polytechnic, Katsina',
    'Kano State Polytechnic, Kano',
    'Lagos State Polytechnic, Ikorodu',
    'Rivers State Polytechnic, Bori',
    'Ramat Polytechnic, Maiduguri',
    'Rufus Giwa Polytechnic, Owo',
    'The Polytechnic, Ibadan',
    'Waziri Umaru Federal Polytechnic, Birnin Kebbi',
  ];
  
  // Polytechnics (Private)
  export const nigerianPolytechnicsPrivate = [
    'Crown Polytechnic, Ado-Ekiti',
    'Heritage Polytechnic, Ikot Udota',
    'The Polytechnic, Ile-Ife',
    'Grace Polytechnic, Lagos',
    'Interlink Polytechnic, Ijebu-Jesa',
    'Nacabs Polytechnic, Akwanga',
    'Sure Foundation Polytechnic, Ikot Akai',
    'Temple Gate Polytechnic, Aba',
    'Wolex Polytechnic, Owerri',
  ];
  
  // Colleges of Education (Public)
  export const nigerianCollegesPublic = [
    'Adeyemi College of Education (ACE), Ondo',
    'Federal College of Education (Technical) Akoka, Lagos (FCE(T) Akoka)',
    'Federal College of Education, Zaria (FCE Zaria)',
    'Alvan Ikoku Federal College of Education (AIFCE), Owerri',
    'Federal College of Education, Kano (FCE Kano)',
    'Federal College of Education, Pankshin, Plateau',
    'Federal College of Education, Yola, Adamawa',
    'Federal College of Education, Eha-Amufu, Enugu',
    'Federal College of Education, Okene, Kogi',
    'Federal College of Education, Katsina, Katsina',
    'Federal College of Education, Asaba, Delta',
    'Federal College of Education, Abeokuta, Ogun',
    'Federal College of Education, Omoku, Rivers',
    'Federal College of Education, Kontagora, Niger',
    'Federal College of Education, Obudu, Cross River',
    'Adeniran Ogunsanya College of Education, Ijanikin',
    'College of Education, Ikere-Ekiti',
    'College of Education, Warri',
    'Emmanuel Alayande College of Education, Oyo',
    'FCT College of Education, Zuba',
    'Nwafor Orizu College of Education, Nsugbe',
  ];
  
  // Colleges of Education (Private)
  export const nigerianCollegesPrivate = [
    'Muftau\' Lanihun College of Education, Ibadan',
    'Havard Wilson College of Education, Aba',
    'Benue State University College of Education, Oju',
    'College of Education, Nsukka',
    'St. Augustine College of Education, Akoka',
  ];
  
  // Colleges of Health Technology (Federal)
  export const nigerianCollegesOfHealthTechFederal = [
    'Federal College of Health Technology, Ilese, Ogun State',
    'Federal College of Health Technology, Makurdi, Benue State',
    'Federal College of Health Technology, Orlu, Imo State',
    'Federal College of Health Technology, Kano',
    'Federal College of Health Technology, Azare, Bauchi State',
    'Federal College of Dental Technology & Therapy, Enugu',
    'Federal School of Medical Laboratory Technology, Jos, Plateau State',
    'Federal College of Veterinary & Medical Laboratory Technology, Vom, Plateau State',
    'Federal College of Orthopaedic Technology, NOH, Igbobi, Lagos',
    'ABUTH School of Health Information Management, Kaduna State',
    'School of Biomedical Engineering Technology, ABUTH, Shika-Zaria, Kaduna',
    'School of Biomedical Engineering Technology, LUTH, Idi Araba, Lagos',
    'School of Biomedical Engineering, UBTH, Benin, Edo',
    'School of Biomedical Engineering, UMTH, Maiduguri, Borno',
    'School of Health Information Management, AKTH, Kano',
    'School of Health Information Management, ATBUTH, Bauchi',
    'School of Health Information Management, NAUTH, Nnewi, Anambra',
    'School of Health Information Management, OAUTH, Ile-Ife, Osun',
    'School of Health Information Management, UBTH, Benin, Edo',
    'School of Health Information Management, UCTH, Calabar, Cross River',
    'School of Health Information Management, UCH, Ibadan, Oyo',
    'School of Health Information Management, UDUTH, Sokoto',
    'School of Health Information Management, UITH, Ilorin, Kwara',
    'School of Health Information Management, UMTH, Maiduguri, Borno',
    'School of Health Information Management, UPTH, Port-Harcourt, Rivers',
    'School of Health Information Management, LUTH, Idi Araba, Lagos',
    'School of Health Information Management, University of Uyo, Uyo',
    'School of Laundry and Dry Cleaning Technology, AKTH, Kano',
    'School of Nursing, Ekiti State University Teaching Hospital, Ado-Ekiti, Ekiti',
    'School of Nursing and Midwifery, A.T.B.U.T.H., Bauchi',
    'School of Nursing, Obafemi Awolowo University OAU Teaching Hospital Complex, Ile-Ife, Osun',
    'School of Orthopaedic Cast Technology, NOH, Enugu',
    'School of Orthopaedic Cast Technology, NOH, Dala, Kano',
    'School of Social Development, UPTH, Port-Harcourt, Rivers',
    'School of Orthopedic Cast Technology, UITH, Ilorin, Kwara',
    'Institute of Health Technology, University Teaching Hospital, Benin, Edo',
    'Nigerian Army School of Medical Sciences, Ojo, Lagos',
    'Nigerian Navy College of Health Sciences, Offa, Kwara',
  ];
  
  // Colleges of Health Technology (State)
  export const nigerianCollegesOfHealthTechState = [
    'Abia State College of Health Technology, Aba',
    'Abia State College of Health Science & Management Technology, Aba',
    'Anambra State College of Health Technology, Obosi',
    'Bauchi State College of Health Technology, Ningi',
    'Bayelsa State College of Health Technology, Otuogidi',
    'Bill and Melinda Gates College of Health Technology, Ningi, Bauchi State',
    'College of Health Technology, Calabar, Cross River State',
    'Cross River State College of Health Technology, Calabar',
    'Delta State College of Health Technology, Ughelli',
    'Delta State School of Health Technology, Ughelli',
    'Ekiti State College of Health Technology, Ijero-Ekiti',
    'Ekiti State College of Health Sciences and Technology, Ijero-Ekiti',
    'Gombe State College of Health Science and Technology, Kaltungo',
    'Imo State College of Health and Management Sciences, Amaigbo',
    'Jigawa State College of Health Technology, Jahun',
    'Kano State College of Health Sciences and Technology, Kano',
    'Katsina State College of Health Sciences and Technology, Daura',
    'Kebbi State College of Health Science and Technology, Jega',
    'Kogi State College of Health Sciences and Technology, Idah',
    'College of Health Science and Technology, Idah, Kogi',
    'Kwara State College of Health Technology, Offa',
    'Lagos State College of Health Technology, Yaba',
    'Nasarawa State College of Health Science and Technology, Keffi',
    'Niger State College of Health Technology, Minna',
    'Ogun State College of Health Technology, Ilese-Ijebu',
    'Ondo State College of Health Technology, Akure',
    'School of Health Technology, Akure, Ondo State',
    'Osun State College of Health Technology, Ilesa',
    'Oyo State College of Health Technology, Eleyele, Ibadan',
    'Oyo State College of Health Science and Technology, Eleyele, Ibadan, Oyo',
    'Plateau State College of Health Technology, Zawan',
    'College of Health Technology, Zawan, Plateau State',
    'Rivers State College of Health Science and Technology, Port Harcourt',
    'Shehu Idris College of Health Sciences & Technology, Makarfi, Kaduna State',
    'Sokoto State College of Health Science and Technology, Gwadabawa',
    'Taraba State College of Health Technology, Takum',
    'Yobe State College of Health Science and Technology, Nguru',
    'Zamfara State College of Health Science and Technology, Tsafe',
    'School of Health Technology, Ilesa, Osun State',
    'School of Health Technology, Daura, Katsina State',
    'School of Health Technology, Etinan, Akwa Ibom State',
    'School of Health Technology, Idah, Kogi State',
    'School of Health Technology, Alushi via Akwanga, Nasarawa State',
    'School of Health Technology, Benin City, Edo State',
    'School of Health Technology, Ijebu-Ode, Ogun State',
    'School of Health Technology, Kankia, Katsina State',
    'School of Health Technology, Minna, Niger State',
    'School of Health Technology, Pankshin, Plateau State',
    'School of Health Technology, Tsafe, Zamfara State',
    'School of Health Technology, Uyo, Akwa Ibom State',
    'School of Health Technology, Yaba, Lagos State',
    'School of Health Technology, Yauri, Kebbi State',
    'School of Health Technology, Zaria, Kaduna State',
    'School of Health Technology, Zuru, Kebbi State',
    'School of Health Technology, Mubi, Adamawa State',
    'School of Health Technology, Maiduguri, Borno State',
    'School of Health Technology, Makurdi, Benue State',
    'School of Health Technology, Nnewi, Anambra State',
    'School of Health Technology, Nsukka, Enugu State',
    'School of Health Technology, Oji River, Enugu State',
    'School of Health Technology, Okene, Kogi State',
    'School of Health Technology, Oyo, Oyo State',
    'School of Health Technology, Port Harcourt, Rivers State',
    'School of Health Technology, Sokoto, Sokoto State',
    'School of Health Technology, Umuahia, Abia State',
    'School of Health Technology, Uromi, Edo State',
    'School of Health Technology, Warri, Delta State',
    'School of Health Technology, Yola, Adamawa State',
    'Kaduna State College of Health Technology, Kaduna',
  ];
  
  // Colleges of Health Technology (Private)
  export const nigerianCollegesOfHealthTechPrivate = [
    'Al-Ma\'arif College of Health Sciences & Technology, Potiskum, Yobe State',
    'Aminu Dabo College of Health Sciences & Technology, Kano State',
    'Babalola Academy College of Health Technology, Ilorin',
    'Bartholomew College of Health Technology, Shao, Kwara State',
    'Centenary College of Health Technology, Emohua, Port Harcourt',
    'College of Health and Technology, Ile-Ife',
    'Dagamas College of Health Science and Technology, Sabon Gari, Zaria, Kaduna State',
    'De-Potter College of Health Technology, Oru Ijebu-Igbo Road, Ogun State',
    'Emirates College of Health Science and Technology, Kano',
    'Ezzangbo College of Health Technology, Ebonyi State',
    'Ezeala College of Nursing Science, Umuseke Njaba LGA, Imo State',
    'Eucharistic Heart College of Health Technology, Orba, Nsukka, Enugu State',
    'Ikirun College of Health Technology, Ikirun, Osun State',
    'Nigerian College of Health Technology, Ilesa',
    'St. Luke\'s College of Health Technology, Anua, Uyo',
    'St. Vincent College of Health Technology, Abakaliki',
    'The College of Health Technology, Oji River, Enugu',
    'Wesley College of Health Technology, Ilesa',
  ];
  
  // Build a single combined institutions list with acronyms
  export const allInstitutions = [
    // Spread all lists
    ...nigerianUniversities,
    ...nigerianPrivateUniversities,
    ...nigerianPolytechnicsPublic,
    ...nigerianPolytechnicsPrivate,
    ...nigerianCollegesPublic,
    ...nigerianCollegesPrivate,
    ...nigerianCollegesOfHealthTechFederal,
    ...nigerianCollegesOfHealthTechState,
    ...nigerianCollegesOfHealthTechPrivate,
    'Other (Not listed)'
  ];
  